name: Go

on:
  push:
    branches: 
      - karsajobs

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - uses: hadolint/hadolint-action@v3.1.0
      name: lint-dockerfile
      with: 
        dockerfile: Dockerfile
    
    - name: test-app
      run: go test -v -short --count=1 $(go list ./...)

    - name: build-app-karsajobs
      run: ./build_push_image_karsajobs.sh
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
